<?php
/**
 * Auto generated by prado-cli.php on 2008-03-18 12:28:13.
 */
class KamarRecord extends TActiveRecord
{
	const TABLE='tbm_kamar';

	public $id;
	public $id_jns_kamar;
	public $nomor_kamar;
	public $lantai;
	public $blok;
	public $max_tamu;
	public $st_smoking;

	public $deleted;
	
	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>
